### ISSUE TITLE
WEB site design was completely changed

### ISSUE THREAD

**Issue by teramonagi** [crubba/Wiley-ADCR#10]
In chapter 15, you deal with the web site
- http://www.dastelefonbuch.de/

.

The current design, however, seems like completely changed compared to what you mentioned in this book.
Do you have old website HTML as a fronzen file?

**Comment by simonmunzert** [comment]
Hi Nagi,
the webpage design has indeed changed completely. To be able to replicate the case study, please have a look at the downloaded HTML files in the attached folder. Writing the functions has become pointless though, as you cannot use them to query new data. We're about to update the examples in the book soon.
Best,
Simon
[phonebook-data.zip](https://github.com/crubba/Wiley-ADCR/files/482513/phonebook-data.zip)
