### ISSUE TITLE
14.1 There is no tweets_oscars.json file on http://www.r-datacollection.com/

### ISSUE THREAD

**Issue by teramonagi** [crubba/Wiley-ADCR#7]
It seems like that tweets_oscars.json does not exist on http://www.r-datacollection.com/.
Could you upload it if it is possible?

**Comment by simonmunzert** [comment]
Hi Nagi,

thanks for the interest in our book. Twitter prohibits publishing of content from their streaming API that contains user-identifiable information. I therefore ripped off some personal variables and uploaded the file here:
https://depot.uni-konstanz.de/cgi-bin/exchange.pl?g=drw7p7frm6 
Please note that I already parsed the json into R to save some space.

Best,
Simon
